apiVersion: v1
kind: Service
metadata:
  name: cifar10-serving
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: cifar10-serving
  ports:
    - name: http
      port: 80
      targetPort: 8080
