FROM python:3.11-slim AS base

WORKDIR /app

COPY requirements/train.txt /app/requirements/train.txt

RUN python -m pip install --no-cache-dir \
    -r /app/requirements/train.txt

FROM base AS training

WORKDIR /app

COPY src/ /app/src/
COPY configs/ /app/configs/

ENV PYTHONUNBUFFERED=1
ENV TRAINING_CONFIG=/app/configs/training_config.yaml

ENTRYPOINT ["python", "src/train.py"]
